<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:http="http://schemas.microsoft.com/ws/06/2004/policy/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.triple-innovations.com/WS/COMMANDO/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" targetNamespace="http://www.triple-innovations.com/WS/COMMANDO/" name="CouponAPI" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsp:Policy wsu:Id="PromotionAPI_Coupon_policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <http:BasicAuthentication />
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsdl:types>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://www.triple-innovations.com/WS/COMMANDO/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:import namespace="http://www.triple-innovations.com/WS/COMMANDO/" />
            <xs:import namespace="http://www.triple-innovations.com/WS/COMMANDO/Types/" />
            <xs:import namespace="http://schemas.datacontract.org/2004/07/CouponDatabase.Lifecycle" />
            <xs:element name="Get">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="PromotionCode" nillable="true" type="xs:string" />
                        <xs:element minOccurs="0" name="CouponCode" nillable="true" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="GetResult" nillable="true" type="tns:Coupon" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetUserCoupons">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="User" nillable="true" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetUserCouponsResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="GetUserCouponsResult" nillable="true" type="tns:ArrayOfCoupon" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Assign">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="PromotionCode" nillable="true" type="xs:string" />
                        <xs:element minOccurs="0" name="CouponCode" nillable="true" type="xs:string" />
                        <xs:element minOccurs="0" name="Holder" nillable="true" type="xs:string" />
                        <xs:element minOccurs="0" name="User" nillable="true" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="AssignResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="AssignResult" nillable="true" type="q1:Command" xmlns:q1="http://schemas.datacontract.org/2004/07/CouponDatabase.Lifecycle" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Validate">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="PromotionCode" nillable="true" type="xs:string" />
                        <xs:element minOccurs="0" name="CouponCode" nillable="true" type="xs:string" />
                        <xs:element minOccurs="0" name="User" nillable="true" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="ValidateResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="ValidateResult" nillable="true" type="q2:Command" xmlns:q2="http://schemas.datacontract.org/2004/07/CouponDatabase.Lifecycle" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Redeem">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="PromotionCode" nillable="true" type="xs:string" />
                        <xs:element minOccurs="0" name="CouponCode" nillable="true" type="xs:string" />
                        <xs:element minOccurs="0" name="User" nillable="true" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="RedeemResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="RedeemResult" nillable="true" type="q3:Command" xmlns:q3="http://schemas.datacontract.org/2004/07/CouponDatabase.Lifecycle" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="UndoRedeem">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="PromotionCode" nillable="true" type="xs:string" />
                        <xs:element minOccurs="0" name="CouponCode" nillable="true" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="UndoRedeemResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="UndoRedeemResult" nillable="true" type="q4:Command" xmlns:q4="http://schemas.datacontract.org/2004/07/CouponDatabase.Lifecycle" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Cancel">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="PromotionCode" nillable="true" type="xs:string" />
                        <xs:element minOccurs="0" name="CouponCode" nillable="true" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="CancelResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="CancelResult" nillable="true" type="q5:Command" xmlns:q5="http://schemas.datacontract.org/2004/07/CouponDatabase.Lifecycle" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:element name="anyType" nillable="true" type="xs:anyType" />
            <xs:element name="anyURI" nillable="true" type="xs:anyURI" />
            <xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
            <xs:element name="boolean" nillable="true" type="xs:boolean" />
            <xs:element name="byte" nillable="true" type="xs:byte" />
            <xs:element name="dateTime" nillable="true" type="xs:dateTime" />
            <xs:element name="decimal" nillable="true" type="xs:decimal" />
            <xs:element name="double" nillable="true" type="xs:double" />
            <xs:element name="float" nillable="true" type="xs:float" />
            <xs:element name="int" nillable="true" type="xs:int" />
            <xs:element name="long" nillable="true" type="xs:long" />
            <xs:element name="QName" nillable="true" type="xs:QName" />
            <xs:element name="short" nillable="true" type="xs:short" />
            <xs:element name="string" nillable="true" type="xs:string" />
            <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
            <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
            <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
            <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort" />
            <xs:element name="char" nillable="true" type="tns:char" />
            <xs:simpleType name="char">
                <xs:restriction base="xs:int" />
            </xs:simpleType>
            <xs:element name="duration" nillable="true" type="tns:duration" />
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid" nillable="true" type="tns:guid" />
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType" type="xs:QName" />
            <xs:attribute name="Id" type="xs:ID" />
            <xs:attribute name="Ref" type="xs:IDREF" />
        </xs:schema>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://www.triple-innovations.com/WS/COMMANDO/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.triple-innovations.com/WS/COMMANDO/" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:import namespace="http://schemas.datacontract.org/2004/07/System" />
            <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
            <xs:complexType name="Coupon" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
                <xs:sequence>
                    <xs:element minOccurs="0" name="Code" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="ExpireDate" type="xs:dateTime" />
                    <xs:element minOccurs="0" name="Holder" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="PromotionCode" nillable="true" type="xs:string" />
                    <xs:element type="q1:CouponStatus" xmlns:q1="http://www.triple-innovations.com/WS/COMMANDO/Types/" name="Status" />
                    <xs:element minOccurs="0" name="User" nillable="true" type="xs:string" />
                </xs:sequence>
            </xs:complexType>
            <xs:element name="Coupon" nillable="true" type="tns:Coupon" />
            <xs:complexType name="ArrayOfCoupon" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
                <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="Coupon" nillable="true" type="tns:Coupon" />
                </xs:sequence>
            </xs:complexType>
            <xs:element name="ArrayOfCoupon" nillable="true" type="tns:ArrayOfCoupon" />
        </xs:schema>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://www.triple-innovations.com/WS/COMMANDO/Types/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.triple-innovations.com/WS/COMMANDO/Types/" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:import namespace="http://schemas.datacontract.org/2004/07/System" />
            <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
            <xs:simpleType name="CouponStatus">
                <xs:restriction  base="xs:string">
                    <xs:enumeration  value="Created" />
                    <xs:enumeration  value="Issued" />
                    <xs:enumeration  value="Redeemed" />
                    <xs:enumeration  value="Canceled" />
                </xs:restriction >
            </xs:simpleType>
            <xs:element name="CouponStatus" type="tns:CouponStatus" />
            <xs:simpleType name="CommandStatus">
                <xs:restriction  base="xs:string">
                    <xs:enumeration  value="Valid" />
                    <xs:enumeration  value="ErrorInvalidStatus" />
                    <xs:enumeration  value="ErrorPromotionNotFound" />
                    <xs:enumeration  value="ErrorCouponNotFound" />
                    <xs:enumeration  value="ErrorInvalidUser" />
                    <xs:enumeration  value="ErrorSystem" />
                </xs:restriction >
            </xs:simpleType>
            <xs:element name="CommandStatus" type="tns:CommandStatus" />
        </xs:schema>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/CouponDatabase.Lifecycle" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/CouponDatabase.Lifecycle" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:import namespace="http://schemas.datacontract.org/2004/07/System" />
            <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
            <xs:complexType name="Command" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/">
                <xs:sequence>
                    <xs:element minOccurs="0" name="Message" nillable="true" type="xs:string" />
                    <xs:element type="q1:CommandStatus" xmlns:q1="http://www.triple-innovations.com/WS/COMMANDO/Types/" name="Status" />
                </xs:sequence>
            </xs:complexType>
            <xs:element name="Command" nillable="true" type="tns:Command" />
        </xs:schema>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
            <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="Coupon_Get_InputMessage">
        <wsdl:part name="parameters" element="tns:Get" />
    </wsdl:message>
    <wsdl:message name="Coupon_Get_OutputMessage">
        <wsdl:part name="parameters" element="tns:GetResponse" />
    </wsdl:message>
    <wsdl:message name="Coupon_GetUserCoupons_InputMessage">
        <wsdl:part name="parameters" element="tns:GetUserCoupons" />
    </wsdl:message>
    <wsdl:message name="Coupon_GetUserCoupons_OutputMessage">
        <wsdl:part name="parameters" element="tns:GetUserCouponsResponse" />
    </wsdl:message>
    <wsdl:message name="Coupon_Assign_InputMessage">
        <wsdl:part name="parameters" element="tns:Assign" />
    </wsdl:message>
    <wsdl:message name="Coupon_Assign_OutputMessage">
        <wsdl:part name="parameters" element="tns:AssignResponse" />
    </wsdl:message>
    <wsdl:message name="Coupon_Validate_InputMessage">
        <wsdl:part name="parameters" element="tns:Validate" />
    </wsdl:message>
    <wsdl:message name="Coupon_Validate_OutputMessage">
        <wsdl:part name="parameters" element="tns:ValidateResponse" />
    </wsdl:message>
    <wsdl:message name="Coupon_Redeem_InputMessage">
        <wsdl:part name="parameters" element="tns:Redeem" />
    </wsdl:message>
    <wsdl:message name="Coupon_Redeem_OutputMessage">
        <wsdl:part name="parameters" element="tns:RedeemResponse" />
    </wsdl:message>
    <wsdl:message name="Coupon_UndoRedeem_InputMessage">
        <wsdl:part name="parameters" element="tns:UndoRedeem" />
    </wsdl:message>
    <wsdl:message name="Coupon_UndoRedeem_OutputMessage">
        <wsdl:part name="parameters" element="tns:UndoRedeemResponse" />
    </wsdl:message>
    <wsdl:message name="Coupon_Cancel_InputMessage">
        <wsdl:part name="parameters" element="tns:Cancel" />
    </wsdl:message>
    <wsdl:message name="Coupon_Cancel_OutputMessage">
        <wsdl:part name="parameters" element="tns:CancelResponse" />
    </wsdl:message>
    <wsdl:portType name="Coupon">
        <wsdl:operation name="Get">
            <wsdl:input wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Get" message="tns:Coupon_Get_InputMessage" />
            <wsdl:output wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/GetResponse" message="tns:Coupon_Get_OutputMessage" />
        </wsdl:operation>
        <wsdl:operation name="GetUserCoupons">
            <wsdl:input wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/GetUserCoupons" message="tns:Coupon_GetUserCoupons_InputMessage" />
            <wsdl:output wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/GetUserCouponsResponse" message="tns:Coupon_GetUserCoupons_OutputMessage" />
        </wsdl:operation>
        <wsdl:operation name="Assign">
            <wsdl:input wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Assign" message="tns:Coupon_Assign_InputMessage" />
            <wsdl:output wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/AssignResponse" message="tns:Coupon_Assign_OutputMessage" />
        </wsdl:operation>
        <wsdl:operation name="Validate">
            <wsdl:input wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Validate" message="tns:Coupon_Validate_InputMessage" />
            <wsdl:output wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/ValidateResponse" message="tns:Coupon_Validate_OutputMessage" />
        </wsdl:operation>
        <wsdl:operation name="Redeem">
            <wsdl:input wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Redeem" message="tns:Coupon_Redeem_InputMessage" />
            <wsdl:output wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/RedeemResponse" message="tns:Coupon_Redeem_OutputMessage" />
        </wsdl:operation>
        <wsdl:operation name="UndoRedeem">
            <wsdl:input wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/UndoRedeem" message="tns:Coupon_UndoRedeem_InputMessage" />
            <wsdl:output wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/UndoRedeemResponse" message="tns:Coupon_UndoRedeem_OutputMessage" />
        </wsdl:operation>
        <wsdl:operation name="Cancel">
            <wsdl:input wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Cancel" message="tns:Coupon_Cancel_InputMessage" />
            <wsdl:output wsam:Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/CancelResponse" message="tns:Coupon_Cancel_OutputMessage" />
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="PromotionAPI" type="tns:Coupon">
        <wsp:PolicyReference URI="#PromotionAPI_Coupon_policy" />
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="Get">
            <soap:operation soapAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Get" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetUserCoupons">
            <soap:operation soapAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/GetUserCoupons" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="Assign">
            <soap:operation soapAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Assign" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="Validate">
            <soap:operation soapAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Validate" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="Redeem">
            <soap:operation soapAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Redeem" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="UndoRedeem">
            <soap:operation soapAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/UndoRedeem" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="Cancel">
            <soap:operation soapAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Cancel" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CouponAPI">
        <wsdl:port name="PromotionAPI" binding="tns:PromotionAPI">
            <soap:address location="https://localhost:44389/CouponAPI" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>