//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coupon", Namespace="http://www.triple-innovations.com/WS/COMMANDO/Types/")]
    public partial class Coupon : object
    {
        
        private bool ActiveField;
        
        private System.DateTime AquireFromField;
        
        private System.DateTime AquireToField;
        
        private System.DateTime AwardFromField;
        
        private System.DateTime AwardToField;
        
        private string CouponMemberField;
        
        private WS.CouponStatus CouponStatusField;
        
        private string HolderField;
        
        private string UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AquireFrom
        {
            get
            {
                return this.AquireFromField;
            }
            set
            {
                this.AquireFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AquireTo
        {
            get
            {
                return this.AquireToField;
            }
            set
            {
                this.AquireToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AwardFrom
        {
            get
            {
                return this.AwardFromField;
            }
            set
            {
                this.AwardFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AwardTo
        {
            get
            {
                return this.AwardToField;
            }
            set
            {
                this.AwardToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Coupon")]
        public string CouponMember
        {
            get
            {
                return this.CouponMemberField;
            }
            set
            {
                this.CouponMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WS.CouponStatus CouponStatus
        {
            get
            {
                return this.CouponStatusField;
            }
            set
            {
                this.CouponStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Holder
        {
            get
            {
                return this.HolderField;
            }
            set
            {
                this.HolderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CouponStatus", Namespace="http://www.triple-innovations.com/WS/COMMANDO/Types/")]
    public enum CouponStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Issued = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Redeemed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Command", Namespace="http://schemas.datacontract.org/2004/07/CouponDatabase.Lifecycle")]
    public partial class Command : object
    {
        
        private string MessageField;
        
        private WS.CommandStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WS.CommandStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandStatus", Namespace="http://www.triple-innovations.com/WS/COMMANDO/Types/")]
    public enum CommandStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Valid = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInvalidStatus = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorPromotionNotFound = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorCouponNotFound = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInvalidUser = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorSystem = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Name="Coupon", Namespace="http://www.triple-innovations.com/WS/COMMANDO/", ConfigurationName="WS.Coupon1")]
    public interface Coupon1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Get", ReplyAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/GetResponse")]
        System.Threading.Tasks.Task<WS.Coupon> GetAsync(string PromotionCode, string CouponCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Assign", ReplyAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/AssignResponse")]
        System.Threading.Tasks.Task<WS.Command> AssignAsync(string PromotionCode, string CouponCode, string Holder, string User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Validate", ReplyAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/ValidateResponse")]
        System.Threading.Tasks.Task<WS.Command> ValidateAsync(string PromotionCode, string CouponCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Redeem", ReplyAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/RedeemResponse")]
        System.Threading.Tasks.Task<WS.Command> RedeemAsync(string PromotionCode, string CouponCode, string User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/UndoRedeem", ReplyAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/UndoRedeemResponse")]
        System.Threading.Tasks.Task<WS.Command> UndoRedeemAsync(string PromotionCode, string CouponCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.triple-innovations.com/WS/COMMANDO/Coupon/Cancel", ReplyAction="http://www.triple-innovations.com/WS/COMMANDO/Coupon/CancelResponse")]
        System.Threading.Tasks.Task<WS.Command> CancelAsync(string PromotionCode, string CouponCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface Coupon1Channel : WS.Coupon1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Coupon1Client : System.ServiceModel.ClientBase<WS.Coupon1>, WS.Coupon1
    {
        
        public Coupon1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WS.Coupon> GetAsync(string PromotionCode, string CouponCode)
        {
            return base.Channel.GetAsync(PromotionCode, CouponCode);
        }
        
        public System.Threading.Tasks.Task<WS.Command> AssignAsync(string PromotionCode, string CouponCode, string Holder, string User)
        {
            return base.Channel.AssignAsync(PromotionCode, CouponCode, Holder, User);
        }
        
        public System.Threading.Tasks.Task<WS.Command> ValidateAsync(string PromotionCode, string CouponCode)
        {
            return base.Channel.ValidateAsync(PromotionCode, CouponCode);
        }
        
        public System.Threading.Tasks.Task<WS.Command> RedeemAsync(string PromotionCode, string CouponCode, string User)
        {
            return base.Channel.RedeemAsync(PromotionCode, CouponCode, User);
        }
        
        public System.Threading.Tasks.Task<WS.Command> UndoRedeemAsync(string PromotionCode, string CouponCode)
        {
            return base.Channel.UndoRedeemAsync(PromotionCode, CouponCode);
        }
        
        public System.Threading.Tasks.Task<WS.Command> CancelAsync(string PromotionCode, string CouponCode)
        {
            return base.Channel.CancelAsync(PromotionCode, CouponCode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
