BEGIN
INSERT INTO "AWARD_CHANNEL" ("ID", "NAME")
VALUES (4, N'Telesales');
INSERT INTO "AWARD_CHANNEL" ("ID", "NAME")
VALUES (3, N'SelfCare');
INSERT INTO "AWARD_CHANNEL" ("ID", "NAME")
VALUES (1, N'POS');
INSERT INTO "AWARD_CHANNEL" ("ID", "NAME")
VALUES (5, N'Webshop');
END;
/

BEGIN
INSERT INTO "ISSUER_CHANNEL" ("ID", "NAME")
VALUES (2, N'Salesforce');
INSERT INTO "ISSUER_CHANNEL" ("ID", "NAME")
VALUES (3, N'SelfCare');
INSERT INTO "ISSUER_CHANNEL" ("ID", "NAME")
VALUES (4, N'Telesales');
INSERT INTO "ISSUER_CHANNEL" ("ID", "NAME")
VALUES (5, N'Webshop');
INSERT INTO "ISSUER_CHANNEL" ("ID", "NAME")
VALUES (1, N'POS');
END;
/


BEGIN
INSERT INTO "PROPERTY" ("ID", "NAME")
VALUES (2, N'NamedHolders');
INSERT INTO "PROPERTY" ("ID", "NAME")
VALUES (4, N'HolderIsOnlyConsumer');
INSERT INTO "PROPERTY" ("ID", "NAME")
VALUES (5, N'AllowMultipleRedeems');
INSERT INTO "PROPERTY" ("ID", "NAME")
VALUES (6, N'AllowCouponSeries');
END;
/
