// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

namespace WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CouponDatabase.Models.AccessLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .HasColumnName("ACTION")
                        .HasMaxLength(80);

                    b.Property<int>("ApplicationType")
                        .HasColumnName("APPLICATION_TYPE");

                    b.Property<string>("Channel")
                        .HasColumnName("CHANNEL")
                        .HasMaxLength(20);

                    b.Property<bool>("Granted")
                        .HasColumnName("GRANTED");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnName("ISSUED_DATE");

                    b.Property<string>("Username")
                        .HasColumnName("USERNAME")
                        .HasMaxLength(20);

                    b.HasKey("Id")
                        .HasName("PK_ACCESS_LOG");

                    b.ToTable("ACCESS_LOG");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Action = "Create Promotion",
                            ApplicationType = 0,
                            Channel = "POS",
                            Granted = false,
                            IssuedDate = new DateTime(2020, 6, 6, 22, 27, 46, 684, DateTimeKind.Local).AddTicks(7673),
                            Username = ""
                        },
                        new
                        {
                            Id = 2L,
                            Action = "Update Coupon",
                            ApplicationType = 1,
                            Channel = "",
                            Granted = false,
                            IssuedDate = new DateTime(2020, 6, 6, 22, 27, 46, 688, DateTimeKind.Local).AddTicks(1070),
                            Username = "korisnik"
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.AwardChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasMaxLength(20);

                    b.HasKey("Id")
                        .HasName("PK_AWARD_CHANNEL");

                    b.ToTable("AWARD_CHANNEL");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "POS"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "SelfCare"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Telesales"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Webshop"
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.Coupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AquireFrom")
                        .HasColumnName("AQUIRE_FROM");

                    b.Property<DateTime?>("AquireTo")
                        .HasColumnName("AQUIRE_TO");

                    b.Property<DateTime?>("AwardFrom")
                        .HasColumnName("AWARD_FROM");

                    b.Property<DateTime?>("AwardTo")
                        .HasColumnName("AWARD_TO");

                    b.Property<string>("Code")
                        .HasColumnName("CODE")
                        .HasMaxLength(40);

                    b.Property<int>("CouponSeries")
                        .HasColumnName("COUPON_SERIES");

                    b.Property<bool>("Enabled")
                        .HasColumnName("ENABLED");

                    b.Property<string>("Holder")
                        .HasColumnName("HOLDER")
                        .HasMaxLength(20);

                    b.Property<int>("MaxRedeemNo")
                        .HasColumnName("MAX_REDEEM_NO");

                    b.Property<long>("PromotionId")
                        .HasColumnName("PROMOTION_ID");

                    b.Property<int>("Status")
                        .HasColumnName("STATUS");

                    b.Property<string>("User")
                        .HasColumnName("USER")
                        .HasMaxLength(20);

                    b.HasKey("Id")
                        .HasName("PK_COUPON");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[CODE] IS NOT NULL");

                    b.HasIndex("PromotionId")
                        .HasName("IX_COUPON_PROMOTION_ID");

                    b.ToTable("COUPON");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567892",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 2,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 3L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567893",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440482",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 2,
                            User = "38640440482"
                        },
                        new
                        {
                            Id = 4L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567894",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440483",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 1,
                            User = "38640440483"
                        },
                        new
                        {
                            Id = 5L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567891",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 4,
                            User = ""
                        },
                        new
                        {
                            Id = 6L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567895",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 3,
                            User = ""
                        },
                        new
                        {
                            Id = 7L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567113",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 3,
                            User = ""
                        },
                        new
                        {
                            Id = 8L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EDOWN1234567892",
                            CouponSeries = 1,
                            Enabled = false,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 5L,
                            Status = 2,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 9L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EDOWN1234567893",
                            CouponSeries = 1,
                            Enabled = false,
                            Holder = "38640440482",
                            MaxRedeemNo = 1,
                            PromotionId = 5L,
                            Status = 2,
                            User = "38640440482"
                        },
                        new
                        {
                            Id = 10L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EDOWN1234567894",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440483",
                            MaxRedeemNo = 1,
                            PromotionId = 5L,
                            Status = 2,
                            User = "38640440483"
                        },
                        new
                        {
                            Id = 11L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EDOWN1234567891",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "",
                            MaxRedeemNo = 1,
                            PromotionId = 5L,
                            Status = 1,
                            User = ""
                        },
                        new
                        {
                            Id = 12L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EDOWN1234567911",
                            CouponSeries = 1,
                            Enabled = false,
                            Holder = "",
                            MaxRedeemNo = 1,
                            PromotionId = 5L,
                            Status = 1,
                            User = ""
                        },
                        new
                        {
                            Id = 13L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EDOWN1234567912",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "",
                            MaxRedeemNo = 1,
                            PromotionId = 5L,
                            Status = 3,
                            User = ""
                        },
                        new
                        {
                            Id = 14L,
                            AquireFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SPRING1234567289",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 1L,
                            Status = 2,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 15L,
                            AquireFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SPRING1234567290",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 1L,
                            Status = 3,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 16L,
                            AquireFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SPRING1234567291",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 1L,
                            Status = 4,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 17L,
                            AquireFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "BLOOM1234567092",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 25L,
                            Status = 1,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 18L,
                            AquireFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "BLOOM1234567291",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 25L,
                            Status = 2,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 19L,
                            AquireFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "BLOOM1234567292",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 25L,
                            Status = 1,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 20L,
                            AquireFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "BLOOM1234567293",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440482",
                            MaxRedeemNo = 1,
                            PromotionId = 25L,
                            Status = 3,
                            User = "38640440482"
                        },
                        new
                        {
                            Id = 21L,
                            AquireFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "BLOOM1234567294",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440482",
                            MaxRedeemNo = 1,
                            PromotionId = 25L,
                            Status = 3,
                            User = "38640440482"
                        },
                        new
                        {
                            Id = 22L,
                            AquireFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SPRING1234567093",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440482",
                            MaxRedeemNo = 1,
                            PromotionId = 1L,
                            Status = 3,
                            User = "38640440482"
                        },
                        new
                        {
                            Id = 23L,
                            AquireFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SPRING1234657291",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440482",
                            MaxRedeemNo = 1,
                            PromotionId = 1L,
                            Status = 4,
                            User = "38640440482"
                        },
                        new
                        {
                            Id = 24L,
                            AquireFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SUMMER1234657390",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440482",
                            MaxRedeemNo = 1,
                            PromotionId = 3L,
                            Status = 1,
                            User = "38640440482"
                        },
                        new
                        {
                            Id = 25L,
                            AquireFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SUMMER1234657391",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 3L,
                            Status = 1,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 26L,
                            AquireFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SUMMER1234657292",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440482",
                            MaxRedeemNo = 1,
                            PromotionId = 3L,
                            Status = 1,
                            User = "38640440482"
                        },
                        new
                        {
                            Id = 27L,
                            AquireFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SUMMER1234657293",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440482",
                            MaxRedeemNo = 1,
                            PromotionId = 3L,
                            Status = 2,
                            User = "38640440482"
                        },
                        new
                        {
                            Id = 28L,
                            AquireFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SUMMER1234657294",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 3L,
                            Status = 4,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 29L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234456294",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 1,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 30L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234456295",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440482",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 1,
                            User = "38640440482"
                        },
                        new
                        {
                            Id = 31L,
                            AquireFrom = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "YEAR12345990",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 26L,
                            Status = 1,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 32L,
                            AquireFrom = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "YEAR12345991",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 26L,
                            Status = 1,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 33L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "YEAR12345992",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 26L,
                            Status = 1,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 34L,
                            AquireFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "YEAR12345994",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 26L,
                            Status = 1,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 35L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "YEAR12345092",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 26L,
                            Status = 1,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 36L,
                            AquireFrom = new DateTime(2020, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "YEAR12345093",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 26L,
                            Status = 1,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 37L,
                            AquireFrom = new DateTime(2020, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "YEAR12345094",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 26L,
                            Status = 1,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 38L,
                            AquireFrom = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "YEAR12345095",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440482",
                            MaxRedeemNo = 1,
                            PromotionId = 26L,
                            Status = 3,
                            User = "38640440482"
                        },
                        new
                        {
                            Id = 39L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567901",
                            CouponSeries = 3,
                            Enabled = false,
                            Holder = "38591641146",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 2,
                            User = "38591641146"
                        },
                        new
                        {
                            Id = 40L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567902",
                            CouponSeries = 3,
                            Enabled = true,
                            Holder = "38591641146",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 2,
                            User = "38591641146"
                        },
                        new
                        {
                            Id = 41L,
                            AquireFrom = new DateTime(2020, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567903",
                            CouponSeries = 3,
                            Enabled = true,
                            Holder = "38591641146",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 1,
                            User = "38591641146"
                        },
                        new
                        {
                            Id = 42L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567904",
                            CouponSeries = 3,
                            Enabled = false,
                            Holder = "38591641147",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 1,
                            User = "38591641147"
                        },
                        new
                        {
                            Id = 43L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567905",
                            CouponSeries = 3,
                            Enabled = true,
                            Holder = "38591641148",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 3,
                            User = "38591641148"
                        },
                        new
                        {
                            Id = 44L,
                            AquireFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "EASTER1234567906",
                            CouponSeries = 3,
                            Enabled = true,
                            Holder = "38591641148",
                            MaxRedeemNo = 1,
                            PromotionId = 2L,
                            Status = 2,
                            User = "38591641148"
                        },
                        new
                        {
                            Id = 45L,
                            AquireFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SPRING1234567190",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 1L,
                            Status = 3,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 46L,
                            AquireFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SPRING1234567191",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440481",
                            MaxRedeemNo = 1,
                            PromotionId = 1L,
                            Status = 2,
                            User = "38640440481"
                        },
                        new
                        {
                            Id = 47L,
                            AquireFrom = new DateTime(2020, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "YEAR12345096",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440487",
                            MaxRedeemNo = 1,
                            PromotionId = 26L,
                            Status = 3,
                            User = "38640440487"
                        },
                        new
                        {
                            Id = 48L,
                            AquireFrom = new DateTime(2020, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "YEAR12345097",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440487",
                            MaxRedeemNo = 1,
                            PromotionId = 26L,
                            Status = 2,
                            User = "38640440487"
                        },
                        new
                        {
                            Id = 49L,
                            AquireFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "BLOOM1234567295",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440485",
                            MaxRedeemNo = 1,
                            PromotionId = 25L,
                            Status = 3,
                            User = "38640440485"
                        },
                        new
                        {
                            Id = 50L,
                            AquireFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "BLOOM1234567296",
                            CouponSeries = 1,
                            Enabled = true,
                            Holder = "38640440486",
                            MaxRedeemNo = 1,
                            PromotionId = 25L,
                            Status = 2,
                            User = "38640440486"
                        },
                        new
                        {
                            Id = 51L,
                            AquireFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SUMMER1234657492",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440484",
                            MaxRedeemNo = 1,
                            PromotionId = 3L,
                            Status = 3,
                            User = "38640440484"
                        },
                        new
                        {
                            Id = 52L,
                            AquireFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AquireTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AwardTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SUMMER1234657493",
                            CouponSeries = 2,
                            Enabled = true,
                            Holder = "38640440485",
                            MaxRedeemNo = 1,
                            PromotionId = 3L,
                            Status = 2,
                            User = "38640440485"
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.CouponAwardChannel", b =>
                {
                    b.Property<long>("CouponId")
                        .HasColumnName("COUPON_ID");

                    b.Property<long>("AwardChannelId")
                        .HasColumnName("AWARD_CHANNEL_ID");

                    b.HasKey("CouponId", "AwardChannelId");

                    b.HasIndex("AwardChannelId")
                        .HasName("IX_COUPON_AWARD_CHANNEL_AWARD_CHANNEL_ID");

                    b.ToTable("COUPON_AWARD_CHANNEL");

                    b.HasData(
                        new
                        {
                            CouponId = 6L,
                            AwardChannelId = 1L
                        },
                        new
                        {
                            CouponId = 7L,
                            AwardChannelId = 5L
                        },
                        new
                        {
                            CouponId = 13L,
                            AwardChannelId = 1L
                        },
                        new
                        {
                            CouponId = 15L,
                            AwardChannelId = 5L
                        },
                        new
                        {
                            CouponId = 20L,
                            AwardChannelId = 3L
                        },
                        new
                        {
                            CouponId = 21L,
                            AwardChannelId = 3L
                        },
                        new
                        {
                            CouponId = 22L,
                            AwardChannelId = 5L
                        },
                        new
                        {
                            CouponId = 38L,
                            AwardChannelId = 1L
                        },
                        new
                        {
                            CouponId = 43L,
                            AwardChannelId = 1L
                        },
                        new
                        {
                            CouponId = 44L,
                            AwardChannelId = 1L
                        },
                        new
                        {
                            CouponId = 45L,
                            AwardChannelId = 3L
                        },
                        new
                        {
                            CouponId = 46L,
                            AwardChannelId = 3L
                        },
                        new
                        {
                            CouponId = 47L,
                            AwardChannelId = 4L
                        },
                        new
                        {
                            CouponId = 48L,
                            AwardChannelId = 4L
                        },
                        new
                        {
                            CouponId = 49L,
                            AwardChannelId = 5L
                        },
                        new
                        {
                            CouponId = 50L,
                            AwardChannelId = 5L
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.CouponHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .HasColumnName("ACTION");

                    b.Property<long>("CouponId")
                        .HasColumnName("COUPON_ID");

                    b.Property<DateTime>("Date")
                        .HasColumnName("DATE");

                    b.Property<int>("Status")
                        .HasColumnName("STATUS");

                    b.Property<string>("User")
                        .HasColumnName("USER");

                    b.HasKey("Id")
                        .HasName("PK_COUPON_HISTORY");

                    b.HasIndex("CouponId")
                        .HasName("IX_COUPON_HISTORY_COUPON_ID");

                    b.ToTable("COUPON_HISTORY");
                });

            modelBuilder.Entity("CouponDatabase.Models.CouponIssuerChannel", b =>
                {
                    b.Property<long>("CouponId")
                        .HasColumnName("COUPON_ID");

                    b.Property<long>("IssuerChannelId")
                        .HasColumnName("ISSUER_CHANNEL_ID");

                    b.HasKey("CouponId", "IssuerChannelId");

                    b.HasIndex("IssuerChannelId")
                        .HasName("IX_COUPON_ISSUER_CHANNEL_ISSUER_CHANNEL_ID");

                    b.ToTable("COUPON_ISSUER_CHANNEL");

                    b.HasData(
                        new
                        {
                            CouponId = 2L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            CouponId = 3L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            CouponId = 4L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            CouponId = 5L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            CouponId = 6L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            CouponId = 7L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            CouponId = 8L,
                            IssuerChannelId = 4L
                        },
                        new
                        {
                            CouponId = 9L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            CouponId = 10L,
                            IssuerChannelId = 2L
                        },
                        new
                        {
                            CouponId = 11L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            CouponId = 12L,
                            IssuerChannelId = 3L
                        },
                        new
                        {
                            CouponId = 13L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            CouponId = 15L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            CouponId = 17L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            CouponId = 18L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            CouponId = 19L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            CouponId = 20L,
                            IssuerChannelId = 3L
                        },
                        new
                        {
                            CouponId = 21L,
                            IssuerChannelId = 3L
                        },
                        new
                        {
                            CouponId = 22L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            CouponId = 38L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            CouponId = 43L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            CouponId = 44L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            CouponId = 45L,
                            IssuerChannelId = 3L
                        },
                        new
                        {
                            CouponId = 46L,
                            IssuerChannelId = 3L
                        },
                        new
                        {
                            CouponId = 47L,
                            IssuerChannelId = 4L
                        },
                        new
                        {
                            CouponId = 48L,
                            IssuerChannelId = 4L
                        },
                        new
                        {
                            CouponId = 49L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            CouponId = 50L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            CouponId = 51L,
                            IssuerChannelId = 2L
                        },
                        new
                        {
                            CouponId = 52L,
                            IssuerChannelId = 2L
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.IssuerChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasMaxLength(20);

                    b.HasKey("Id")
                        .HasName("PK_ISSUER_CHANNEL");

                    b.ToTable("ISSUER_CHANNEL");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "POS"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Salesforce"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "SelfCare"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Telesales"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Webshop"
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.NotifyList", b =>
                {
                    b.Property<long>("SystemId")
                        .HasColumnName("SYSTEM_ID");

                    b.Property<long>("ChannelId")
                        .HasColumnName("CHANNEL_ID");

                    b.Property<string>("Url")
                        .HasColumnName("URL");

                    b.HasKey("SystemId", "ChannelId");

                    b.HasIndex("ChannelId")
                        .HasName("IX_NOTIFY_LIST_CHANNEL_ID");

                    b.ToTable("NOTIFY_LIST");
                });

            modelBuilder.Entity("CouponDatabase.Models.Promotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("CODE")
                        .HasMaxLength(40);

                    b.Property<int>("CouponSeries")
                        .HasColumnName("COUPON_SERIES");

                    b.Property<bool>("Enabled")
                        .HasColumnName("ENABLED");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnName("VALID_FROM");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnName("VALID_TO");

                    b.HasKey("Id")
                        .HasName("PK_PROMOTION");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PROMOTION");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "Spring",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            Code = "Easter",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            Code = "Summer",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            Code = "SpringDown",
                            CouponSeries = 0,
                            Enabled = false,
                            ValidFrom = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            Code = "EasterDown",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6L,
                            Code = "SummerDown",
                            CouponSeries = 0,
                            Enabled = false,
                            ValidFrom = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7L,
                            Code = "FUNZIES!",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8L,
                            Code = "NOTfunzies",
                            CouponSeries = 0,
                            Enabled = false,
                            ValidFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9L,
                            Code = "Summer3",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10L,
                            Code = "Spring4",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11L,
                            Code = "Easter4",
                            CouponSeries = 0,
                            Enabled = false,
                            ValidFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12L,
                            Code = "Summer4",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13L,
                            Code = "Spring5",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14L,
                            Code = "Easter5",
                            CouponSeries = 0,
                            Enabled = false,
                            ValidFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15L,
                            Code = "Summer5",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16L,
                            Code = "Spring6",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17L,
                            Code = "Easter6",
                            CouponSeries = 0,
                            Enabled = false,
                            ValidFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18L,
                            Code = "Summer6",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19L,
                            Code = "Spring7",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20L,
                            Code = "Easter7",
                            CouponSeries = 0,
                            Enabled = false,
                            ValidFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21L,
                            Code = "Summer7",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22L,
                            Code = "Spring8",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23L,
                            Code = "Easter8",
                            CouponSeries = 0,
                            Enabled = false,
                            ValidFrom = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24L,
                            Code = "Summer8",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25L,
                            Code = "Bloom",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26L,
                            Code = "AllYear",
                            CouponSeries = 0,
                            Enabled = true,
                            ValidFrom = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.PromotionAwardChannel", b =>
                {
                    b.Property<long>("PromotionId")
                        .HasColumnName("PROMOTION_ID");

                    b.Property<long>("AwardChannelId")
                        .HasColumnName("AWARD_CHANNEL_ID");

                    b.HasKey("PromotionId", "AwardChannelId");

                    b.HasIndex("AwardChannelId")
                        .HasName("IX_PROMOTION_AWARD_CHANNEL_AWARD_CHANNEL_ID");

                    b.ToTable("PROMOTION_AWARD_CHANNEL");

                    b.HasData(
                        new
                        {
                            PromotionId = 1L,
                            AwardChannelId = 1L
                        },
                        new
                        {
                            PromotionId = 1L,
                            AwardChannelId = 3L
                        },
                        new
                        {
                            PromotionId = 1L,
                            AwardChannelId = 5L
                        },
                        new
                        {
                            PromotionId = 2L,
                            AwardChannelId = 3L
                        },
                        new
                        {
                            PromotionId = 2L,
                            AwardChannelId = 4L
                        },
                        new
                        {
                            PromotionId = 2L,
                            AwardChannelId = 5L
                        },
                        new
                        {
                            PromotionId = 11L,
                            AwardChannelId = 1L
                        },
                        new
                        {
                            PromotionId = 3L,
                            AwardChannelId = 1L
                        },
                        new
                        {
                            PromotionId = 3L,
                            AwardChannelId = 4L
                        },
                        new
                        {
                            PromotionId = 3L,
                            AwardChannelId = 3L
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.PromotionIssuerChannel", b =>
                {
                    b.Property<long>("PromotionId")
                        .HasColumnName("PROMOTION_ID");

                    b.Property<long>("IssuerChannelId")
                        .HasColumnName("ISSUER_CHANNEL_ID");

                    b.HasKey("PromotionId", "IssuerChannelId");

                    b.HasIndex("IssuerChannelId")
                        .HasName("IX_PROMOTION_ISSUER_CHANNEL_ISSUER_CHANNEL_ID");

                    b.ToTable("PROMOTION_ISSUER_CHANNEL");

                    b.HasData(
                        new
                        {
                            PromotionId = 1L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            PromotionId = 1L,
                            IssuerChannelId = 2L
                        },
                        new
                        {
                            PromotionId = 1L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            PromotionId = 2L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            PromotionId = 2L,
                            IssuerChannelId = 4L
                        },
                        new
                        {
                            PromotionId = 2L,
                            IssuerChannelId = 5L
                        },
                        new
                        {
                            PromotionId = 11L,
                            IssuerChannelId = 2L
                        },
                        new
                        {
                            PromotionId = 3L,
                            IssuerChannelId = 1L
                        },
                        new
                        {
                            PromotionId = 3L,
                            IssuerChannelId = 4L
                        },
                        new
                        {
                            PromotionId = 3L,
                            IssuerChannelId = 5L
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.PromotionProperty", b =>
                {
                    b.Property<long>("PromotionId")
                        .HasColumnName("PROMOTION_ID");

                    b.Property<long>("PropertyId")
                        .HasColumnName("PROPERTY_ID");

                    b.HasKey("PromotionId", "PropertyId");

                    b.HasIndex("PropertyId")
                        .HasName("IX_PROMOTION_PROPERTY_PROPERTY_ID");

                    b.ToTable("PROMOTION_PROPERTY");

                    b.HasData(
                        new
                        {
                            PromotionId = 1L,
                            PropertyId = 2L
                        },
                        new
                        {
                            PromotionId = 1L,
                            PropertyId = 4L
                        },
                        new
                        {
                            PromotionId = 2L,
                            PropertyId = 6L
                        },
                        new
                        {
                            PromotionId = 2L,
                            PropertyId = 1L
                        },
                        new
                        {
                            PromotionId = 7L,
                            PropertyId = 2L
                        },
                        new
                        {
                            PromotionId = 5L,
                            PropertyId = 4L
                        },
                        new
                        {
                            PromotionId = 3L,
                            PropertyId = 6L
                        },
                        new
                        {
                            PromotionId = 11L,
                            PropertyId = 1L
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasMaxLength(20);

                    b.HasKey("Id")
                        .HasName("PK_PROPERTY");

                    b.ToTable("PROPERTY");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "UniqueCoupons"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "NamedHolders"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "NamedConsumers"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "HolderIsOnlyConsumer"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "AllowMultipleRedeems"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "AllowCouponSeries"
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.System", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .HasColumnName("PASSWORD")
                        .HasMaxLength(20);

                    b.Property<string>("Username")
                        .HasColumnName("USERNAME")
                        .HasMaxLength(20);

                    b.HasKey("Id")
                        .HasName("PK_SYSTEM");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[NAME] IS NOT NULL");

                    b.ToTable("SYSTEM");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "CRM",
                            Password = "test",
                            Username = "max"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "SalesForce",
                            Password = "test",
                            Username = "sf"
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("USERNAME")
                        .HasMaxLength(20);

                    b.Property<int>("AccessType")
                        .HasColumnName("ACCESS_TYPE");

                    b.Property<string>("Domain")
                        .HasColumnName("DOMAIN")
                        .HasMaxLength(20);

                    b.Property<string>("Fullname")
                        .HasColumnName("FULLNAME")
                        .HasMaxLength(80);

                    b.HasKey("Username");

                    b.ToTable("USER");

                    b.HasData(
                        new
                        {
                            Username = "ljubo",
                            AccessType = 1,
                            Domain = "LJUBO-PC",
                            Fullname = "Ljubomir Kraljevic"
                        },
                        new
                        {
                            Username = "traktor",
                            AccessType = 1,
                            Domain = "LJUBO-PC",
                            Fullname = "DJ Fresh Prince"
                        });
                });

            modelBuilder.Entity("CouponDatabase.Models.Coupon", b =>
                {
                    b.HasOne("CouponDatabase.Models.Promotion", "Promotion")
                        .WithMany("Coupons")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK_COUPON_PROMOTION_PROMOTION_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CouponDatabase.Models.CouponAwardChannel", b =>
                {
                    b.HasOne("CouponDatabase.Models.AwardChannel", "AwardChannel")
                        .WithMany()
                        .HasForeignKey("AwardChannelId")
                        .HasConstraintName("FK_COUPON_AWARD_CHANNEL_AWARD_CHANNEL_AWARD_CHANNEL_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CouponDatabase.Models.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .HasConstraintName("FK_COUPON_AWARD_CHANNEL_COUPON_COUPON_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CouponDatabase.Models.CouponHistory", b =>
                {
                    b.HasOne("CouponDatabase.Models.Coupon", "Coupon")
                        .WithMany("CouponHistories")
                        .HasForeignKey("CouponId")
                        .HasConstraintName("FK_COUPON_HISTORY_COUPON_COUPON_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CouponDatabase.Models.CouponIssuerChannel", b =>
                {
                    b.HasOne("CouponDatabase.Models.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .HasConstraintName("FK_COUPON_ISSUER_CHANNEL_COUPON_COUPON_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CouponDatabase.Models.IssuerChannel", "IssuerChannel")
                        .WithMany()
                        .HasForeignKey("IssuerChannelId")
                        .HasConstraintName("FK_COUPON_ISSUER_CHANNEL_ISSUER_CHANNEL_ISSUER_CHANNEL_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CouponDatabase.Models.NotifyList", b =>
                {
                    b.HasOne("CouponDatabase.Models.IssuerChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .HasConstraintName("FK_NOTIFY_LIST_ISSUER_CHANNEL_CHANNEL_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CouponDatabase.Models.System", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .HasConstraintName("FK_NOTIFY_LIST_SYSTEM_SYSTEM_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CouponDatabase.Models.PromotionAwardChannel", b =>
                {
                    b.HasOne("CouponDatabase.Models.AwardChannel", "AwardChannel")
                        .WithMany()
                        .HasForeignKey("AwardChannelId")
                        .HasConstraintName("FK_PROMOTION_AWARD_CHANNEL_AWARD_CHANNEL_AWARD_CHANNEL_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CouponDatabase.Models.Promotion", "Promotion")
                        .WithMany("PromotionAwardChannels")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK_PROMOTION_AWARD_CHANNEL_PROMOTION_PROMOTION_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CouponDatabase.Models.PromotionIssuerChannel", b =>
                {
                    b.HasOne("CouponDatabase.Models.IssuerChannel", "IssuerChannel")
                        .WithMany()
                        .HasForeignKey("IssuerChannelId")
                        .HasConstraintName("FK_PROMOTION_ISSUER_CHANNEL_ISSUER_CHANNEL_ISSUER_CHANNEL_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CouponDatabase.Models.Promotion", "Promotion")
                        .WithMany("PromotionIssuerChannels")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK_PROMOTION_ISSUER_CHANNEL_PROMOTION_PROMOTION_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CouponDatabase.Models.PromotionProperty", b =>
                {
                    b.HasOne("CouponDatabase.Models.Promotion", "Promotion")
                        .WithMany("PromotionProperties")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK_PROMOTION_PROPERTY_PROMOTION_PROMOTION_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CouponDatabase.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .HasConstraintName("FK_PROMOTION_PROPERTY_PROPERTY_PROPERTY_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
