//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripleI.CouponDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TripleI.CouponDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string CouponStatus_Canceled {
            get {
                return ResourceManager.GetString("CouponStatus.Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued.
        /// </summary>
        internal static string CouponStatus_Issued {
            get {
                return ResourceManager.GetString("CouponStatus.Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string CouponStatus_Open {
            get {
                return ResourceManager.GetString("CouponStatus.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemed.
        /// </summary>
        internal static string CouponStatus_Redeemed {
            get {
                return ResourceManager.GetString("CouponStatus.Redeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is not allowed for the channel:.
        /// </summary>
        internal static string ErrorInvalidChannel_Message {
            get {
                return ResourceManager.GetString("ErrorInvalidChannel.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon status change is not allowed:.
        /// </summary>
        internal static string ErrorInvalidStatus_Message {
            get {
                return ResourceManager.GetString("ErrorInvalidStatus.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is not allowed for the user:.
        /// </summary>
        internal static string ErrorInvalidUser_Message {
            get {
                return ResourceManager.GetString("ErrorInvalidUser.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion was not found for the code:.
        /// </summary>
        internal static string ErrorPromotionNotFound_Message {
            get {
                return ResourceManager.GetString("ErrorPromotionNotFound.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string LifecycleAction_Assign {
            get {
                return ResourceManager.GetString("LifecycleAction.Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string LifecycleAction_Cancel {
            get {
                return ResourceManager.GetString("LifecycleAction.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem.
        /// </summary>
        internal static string LifecycleAction_Redeem {
            get {
                return ResourceManager.GetString("LifecycleAction.Redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndoRedeem.
        /// </summary>
        internal static string LifecycleAction_UndoRedeem {
            get {
                return ResourceManager.GetString("LifecycleAction.UndoRedeem", resourceCulture);
            }
        }
    }
}
