//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CouponDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Series.
        /// </summary>
        public static string Btn_AddSeries {
            get {
                return ResourceManager.GetString("Btn.AddSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filters.
        /// </summary>
        public static string Btn_ApplyFilters {
            get {
                return ResourceManager.GetString("Btn.ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create And Add Series.
        /// </summary>
        public static string Btn_CreateAndAddSeries {
            get {
                return ResourceManager.GetString("Btn.CreateAndAddSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Btn_CreateNew {
            get {
                return ResourceManager.GetString("Btn.CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Btn_Disable {
            get {
                return ResourceManager.GetString("Btn.Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Btn_Enable {
            get {
                return ResourceManager.GetString("Btn.Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Btn_Filter {
            get {
                return ResourceManager.GetString("Btn.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Btn_Generate {
            get {
                return ResourceManager.GetString("Btn.Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Btn_Import {
            get {
                return ResourceManager.GetString("Btn.Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Btn_SaveChanges {
            get {
                return ResourceManager.GetString("Btn.SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string CouponStatus_Canceled {
            get {
                return ResourceManager.GetString("CouponStatus.Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued.
        /// </summary>
        public static string CouponStatus_Issued {
            get {
                return ResourceManager.GetString("CouponStatus.Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string CouponStatus_Open {
            get {
                return ResourceManager.GetString("CouponStatus.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemed.
        /// </summary>
        public static string CouponStatus_Redeemed {
            get {
                return ResourceManager.GetString("CouponStatus.Redeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is not allowed for the channel:.
        /// </summary>
        public static string ErrorInvalidChannel_Message {
            get {
                return ResourceManager.GetString("ErrorInvalidChannel.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon status change is not allowed:.
        /// </summary>
        public static string ErrorInvalidStatus_Message {
            get {
                return ResourceManager.GetString("ErrorInvalidStatus.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is not allowed for the user:.
        /// </summary>
        public static string ErrorInvalidUser_Message {
            get {
                return ResourceManager.GetString("ErrorInvalidUser.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion was not found for the code:.
        /// </summary>
        public static string ErrorPromotionNotFound_Message {
            get {
                return ResourceManager.GetString("ErrorPromotionNotFound.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string LifecycleAction_Assign {
            get {
                return ResourceManager.GetString("LifecycleAction.Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LifecycleAction_Cancel {
            get {
                return ResourceManager.GetString("LifecycleAction.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem.
        /// </summary>
        public static string LifecycleAction_Redeem {
            get {
                return ResourceManager.GetString("LifecycleAction.Redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndoRedeem.
        /// </summary>
        public static string LifecycleAction_UndoRedeem {
            get {
                return ResourceManager.GetString("LifecycleAction.UndoRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Nav_Administration {
            get {
                return ResourceManager.GetString("Nav.Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifecycle.
        /// </summary>
        public static string Nav_Lifecycle {
            get {
                return ResourceManager.GetString("Nav.Lifecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in as .
        /// </summary>
        public static string Nav_LoggedIn {
            get {
                return ResourceManager.GetString("Nav.LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Nav_Management {
            get {
                return ResourceManager.GetString("Nav.Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Issuer.
        /// </summary>
        public static string Promotion_AllowedIssuer {
            get {
                return ResourceManager.GetString("Promotion.AllowedIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed User.
        /// </summary>
        public static string Promotion_AllowedUser {
            get {
                return ResourceManager.GetString("Promotion.AllowedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Promotion_Code {
            get {
                return ResourceManager.GetString("Promotion.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is 20 characters.
        /// </summary>
        public static string Promotion_Code_Length {
            get {
                return ResourceManager.GetString("Promotion.Code.Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Code is required..
        /// </summary>
        public static string Promotion_Code_Required {
            get {
                return ResourceManager.GetString("Promotion.Code.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Promotion_Properties {
            get {
                return ResourceManager.GetString("Promotion.Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This promotion has a set end date.
        /// </summary>
        public static string Promotion_SetEndDateChkLabel {
            get {
                return ResourceManager.GetString("Promotion.SetEndDateChkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Promotion_StatusDisabled {
            get {
                return ResourceManager.GetString("Promotion.StatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Promotion_StatusEnabled {
            get {
                return ResourceManager.GetString("Promotion.StatusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Promotion.
        /// </summary>
        public static string Promotion_TitleCreate {
            get {
                return ResourceManager.GetString("Promotion.TitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Promotion.
        /// </summary>
        public static string Promotion_TitleEdit {
            get {
                return ResourceManager.GetString("Promotion.TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string Promotions_Title {
            get {
                return ResourceManager.GetString("Promotions.Title", resourceCulture);
            }
        }
    }
}
