//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CouponDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify List.
        /// </summary>
        public static string Administration_ChannelsNotifyList {
            get {
                return ResourceManager.GetString("Administration_ChannelsNotifyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systems.
        /// </summary>
        public static string Administration_ChannelsSystems {
            get {
                return ResourceManager.GetString("Administration_ChannelsSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Series.
        /// </summary>
        public static string Btn_AddSeries {
            get {
                return ResourceManager.GetString("Btn_AddSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add System.
        /// </summary>
        public static string Btn_AddSystem {
            get {
                return ResourceManager.GetString("Btn_AddSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Notify List.
        /// </summary>
        public static string Btn_AddToNotifyList {
            get {
                return ResourceManager.GetString("Btn_AddToNotifyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filters.
        /// </summary>
        public static string Btn_ApplyFilters {
            get {
                return ResourceManager.GetString("Btn_ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create And Add Series.
        /// </summary>
        public static string Btn_CreateAndAddSeries {
            get {
                return ResourceManager.GetString("Btn_CreateAndAddSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Btn_CreateNew {
            get {
                return ResourceManager.GetString("Btn_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Btn_Disable {
            get {
                return ResourceManager.GetString("Btn_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Btn_Enable {
            get {
                return ResourceManager.GetString("Btn_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Btn_Export {
            get {
                return ResourceManager.GetString("Btn_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Btn_Filter {
            get {
                return ResourceManager.GetString("Btn_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Btn_Generate {
            get {
                return ResourceManager.GetString("Btn_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Btn_Import {
            get {
                return ResourceManager.GetString("Btn_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Btn_Remove {
            get {
                return ResourceManager.GetString("Btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace File.
        /// </summary>
        public static string Btn_ReplaceFile {
            get {
                return ResourceManager.GetString("Btn_ReplaceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Changes.
        /// </summary>
        public static string Btn_ResetChanges {
            get {
                return ResourceManager.GetString("Btn_ResetChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Btn_SaveChanges {
            get {
                return ResourceManager.GetString("Btn_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string Btn_SelectFile {
            get {
                return ResourceManager.GetString("Btn_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Disabled.
        /// </summary>
        public static string Btn_SetDisabled {
            get {
                return ResourceManager.GetString("Btn_SetDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Enabled.
        /// </summary>
        public static string Btn_SetEnabled {
            get {
                return ResourceManager.GetString("Btn_SetEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Btn_Update {
            get {
                return ResourceManager.GetString("Btn_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Selected.
        /// </summary>
        public static string Btn_UpdateSelected {
            get {
                return ResourceManager.GetString("Btn_UpdateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string CouponFilter_Search {
            get {
                return ResourceManager.GetString("CouponFilter_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons didn&apos;t inserted..
        /// </summary>
        public static string CouponInsertFailed_Message {
            get {
                return ResourceManager.GetString("CouponInsertFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Coupon Series.
        /// </summary>
        public static string CouponSeries_TitleCreate {
            get {
                return ResourceManager.GetString("CouponSeries_TitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {0} to.
        /// </summary>
        public static string CouponsModal_SetTo {
            get {
                return ResourceManager.GetString("CouponsModal_SetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string CouponStatus_Canceled {
            get {
                return ResourceManager.GetString("CouponStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued.
        /// </summary>
        public static string CouponStatus_Issued {
            get {
                return ResourceManager.GetString("CouponStatus_Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string CouponStatus_Open {
            get {
                return ResourceManager.GetString("CouponStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemed.
        /// </summary>
        public static string CouponStatus_Redeemed {
            get {
                return ResourceManager.GetString("CouponStatus_Redeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignable from.
        /// </summary>
        public static string Date_AssignableFrom {
            get {
                return ResourceManager.GetString("Date_AssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignable until.
        /// </summary>
        public static string Date_AssignableTo {
            get {
                return ResourceManager.GetString("Date_AssignableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemable from.
        /// </summary>
        public static string Date_RedeemableFrom {
            get {
                return ResourceManager.GetString("Date_RedeemableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemable until.
        /// </summary>
        public static string Date_RedeemableTo {
            get {
                return ResourceManager.GetString("Date_RedeemableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        public static string Date_ValidFrom {
            get {
                return ResourceManager.GetString("Date_ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        public static string Date_ValidTo {
            get {
                return ResourceManager.GetString("Date_ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon not found in Database..
        /// </summary>
        public static string ErrorCouponNotFound_Message {
            get {
                return ResourceManager.GetString("ErrorCouponNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is not allowed for the channel:.
        /// </summary>
        public static string ErrorInvalidChannel_Message {
            get {
                return ResourceManager.GetString("ErrorInvalidChannel_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon status change is not allowed:.
        /// </summary>
        public static string ErrorInvalidStatus_Message {
            get {
                return ResourceManager.GetString("ErrorInvalidStatus_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is not allowed for the user:.
        /// </summary>
        public static string ErrorInvalidUser_Message {
            get {
                return ResourceManager.GetString("ErrorInvalidUser_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion was not found for the code:.
        /// </summary>
        public static string ErrorPromotionNotFound_Message {
            get {
                return ResourceManager.GetString("ErrorPromotionNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active/Inactive.
        /// </summary>
        public static string Filter_ActiveInactive {
            get {
                return ResourceManager.GetString("Filter_ActiveInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Code.
        /// </summary>
        public static string Filter_ByCode {
            get {
                return ResourceManager.GetString("Filter_ByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Property.
        /// </summary>
        public static string Filter_ByProperty {
            get {
                return ResourceManager.GetString("Filter_ByProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By State.
        /// </summary>
        public static string Filter_ByState {
            get {
                return ResourceManager.GetString("Filter_ByState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search returned no results..
        /// </summary>
        public static string Filter_NoResults {
            get {
                return ResourceManager.GetString("Filter_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string LifecycleAction_Assign {
            get {
                return ResourceManager.GetString("LifecycleAction_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LifecycleAction_Cancel {
            get {
                return ResourceManager.GetString("LifecycleAction_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem.
        /// </summary>
        public static string LifecycleAction_Redeem {
            get {
                return ResourceManager.GetString("LifecycleAction_Redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndoRedeem.
        /// </summary>
        public static string LifecycleAction_UndoRedeem {
            get {
                return ResourceManager.GetString("LifecycleAction_UndoRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Details.
        /// </summary>
        public static string LifecycleCouponFilter_Title {
            get {
                return ResourceManager.GetString("LifecycleCouponFilter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Details.
        /// </summary>
        public static string LifecyclePromotionFilter_Title {
            get {
                return ResourceManager.GetString("LifecyclePromotionFilter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will disable promotion until turned back on..
        /// </summary>
        public static string Modal_ContentDisable {
            get {
                return ResourceManager.GetString("Modal_ContentDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will enable promotion until turned back off..
        /// </summary>
        public static string Modal_ContentEnable {
            get {
                return ResourceManager.GetString("Modal_ContentEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you shure you want to remove this notify list?.
        /// </summary>
        public static string Modal_ContentRemoveNotifyList {
            get {
                return ResourceManager.GetString("Modal_ContentRemoveNotifyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you shure you want to remove this system?.
        /// </summary>
        public static string Modal_ContentRemoveSystem {
            get {
                return ResourceManager.GetString("Modal_ContentRemoveSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add System.
        /// </summary>
        public static string Modal_HeadingAddSystem {
            get {
                return ResourceManager.GetString("Modal_HeadingAddSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Notify List.
        /// </summary>
        public static string Modal_HeadingAddToNotifyList {
            get {
                return ResourceManager.GetString("Modal_HeadingAddToNotifyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a Notify List.
        /// </summary>
        public static string Modal_HeadingEditANotifyList {
            get {
                return ResourceManager.GetString("Modal_HeadingEditANotifyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditSystem.
        /// </summary>
        public static string Modal_HeadingEditSystem {
            get {
                return ResourceManager.GetString("Modal_HeadingEditSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove notify list.
        /// </summary>
        public static string Modal_HeadingRemoveNotifyList {
            get {
                return ResourceManager.GetString("Modal_HeadingRemoveNotifyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove system.
        /// </summary>
        public static string Modal_HeadingRemoveSystem {
            get {
                return ResourceManager.GetString("Modal_HeadingRemoveSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set disabled?.
        /// </summary>
        public static string Modal_TitleSetDisabled {
            get {
                return ResourceManager.GetString("Modal_TitleSetDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set enabled?.
        /// </summary>
        public static string Modal_TitleSetEnabled {
            get {
                return ResourceManager.GetString("Modal_TitleSetEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Nav_Administration {
            get {
                return ResourceManager.GetString("Nav_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access History.
        /// </summary>
        public static string Nav_AdministrationAccessHistory {
            get {
                return ResourceManager.GetString("Nav_AdministrationAccessHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string Nav_AdministrationChannels {
            get {
                return ResourceManager.GetString("Nav_AdministrationChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Nav_AdministrationUsers {
            get {
                return ResourceManager.GetString("Nav_AdministrationUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifecycle.
        /// </summary>
        public static string Nav_Lifecycle {
            get {
                return ResourceManager.GetString("Nav_Lifecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in as .
        /// </summary>
        public static string Nav_LoggedIn {
            get {
                return ResourceManager.GetString("Nav_LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Nav_Management {
            get {
                return ResourceManager.GetString("Nav_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Issuer.
        /// </summary>
        public static string Promotion_AllowedIssuer {
            get {
                return ResourceManager.GetString("Promotion_AllowedIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed User.
        /// </summary>
        public static string Promotion_AllowedUser {
            get {
                return ResourceManager.GetString("Promotion_AllowedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Promotion_Code {
            get {
                return ResourceManager.GetString("Promotion_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is 20 characters.
        /// </summary>
        public static string Promotion_Code_Length {
            get {
                return ResourceManager.GetString("Promotion_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Code is required..
        /// </summary>
        public static string Promotion_Code_Required {
            get {
                return ResourceManager.GetString("Promotion_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Promotion_Properties {
            get {
                return ResourceManager.GetString("Promotion_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This promotion has a set end date.
        /// </summary>
        public static string Promotion_SetEndDateChkLabel {
            get {
                return ResourceManager.GetString("Promotion_SetEndDateChkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Promotion_StatusDisabled {
            get {
                return ResourceManager.GetString("Promotion_StatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Promotion_StatusEnabled {
            get {
                return ResourceManager.GetString("Promotion_StatusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Promotion.
        /// </summary>
        public static string Promotion_TitleCreate {
            get {
                return ResourceManager.GetString("Promotion_TitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Promotion.
        /// </summary>
        public static string Promotion_TitleEdit {
            get {
                return ResourceManager.GetString("Promotion_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion didn&apos;t inserted..
        /// </summary>
        public static string PromotionInsertFailed_Message {
            get {
                return ResourceManager.GetString("PromotionInsertFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string Promotions_Title {
            get {
                return ResourceManager.GetString("Promotions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion didn&apos;t saved..
        /// </summary>
        public static string PromotionUpdateFailed_Message {
            get {
                return ResourceManager.GetString("PromotionUpdateFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use letters.
        /// </summary>
        public static string SeriesGenerate_UseLetters {
            get {
                return ResourceManager.GetString("SeriesGenerate_UseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use numbers.
        /// </summary>
        public static string SeriesGenerate_UseNumbers {
            get {
                return ResourceManager.GetString("SeriesGenerate_UseNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Valid_Message {
            get {
                return ResourceManager.GetString("Valid_Message", resourceCulture);
            }
        }
    }
}
